services:
  roach-init:
    image: cockroachdb/cockroach:v25.3.4
    container_name: roach-init
    networks:
        - backend_network
    entrypoint: []
    volumes:
      - ./scripts/init-cluster.sh:/usr/local/bin/init-cluster.sh
    command: /usr/local/bin/init-cluster.sh
    depends_on:
      roach1:
        condition: service_healthy
      roach2:
        condition: service_healthy

  roach1:
    image: cockroachdb/cockroach:v25.3.4
    container_name: roach1
    hostname: roach1
    networks:
        - backend_network
    ports:
        - "26257:26257"
        - "8080:8080"
    volumes:
        - roach1:/cockroach/cockroach-data
    command: >
        start
        --advertise-addr=roach1:26357
        --http-addr=roach1:8080
        --listen-addr=roach1:26357
        --sql-addr=roach1:26257
        --insecure
        --join=roach1:26357,roach2:26357
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://roach1:8080/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  roach2:
    image: cockroachdb/cockroach:v25.3.4
    container_name: roach2
    hostname: roach2
    networks:
        - backend_network
    ports:
        - "26258:26258"
        - "8081:8081"
    volumes:
        - roach2:/cockroach/cockroach-data
    command: >
        start
        --advertise-addr=roach2:26357
        --http-addr=roach2:8081
        --listen-addr=roach2:26357
        --sql-addr=roach2:26258
        --insecure
        --join=roach1:26357,roach2:26357
    depends_on:
        - roach1
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://roach2:8081/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  kafka:
    image: confluentinc/cp-kafka:8.1.0
    container_name: kafka
    hostname: kafka
    networks:
      - backend_network
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    restart: on-failure
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 15s
      timeout: 10s
      retries: 5

  kafka-init:
    image: confluentinc/cp-kafka:8.1.0
    container_name: kafka-init
    networks:
      - backend_network
    volumes:
      - ./scripts/create-kafka-topics.sh:/usr/local/bin/create-kafka-topics.sh
    command: /usr/local/bin/create-kafka-topics.sh
    depends_on:
      kafka:
        condition: service_healthy

  api:
    build: ./api
    container_name: api
    ports:
      - "8090:8090"
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      roach-init:
        condition: service_completed_successfully
    environment:
      - PORT=8090
      - KAFKA_HOST=kafka
      - KAFKA_PORT=29092
      - DB_HOST=roach1
      - DB_PORT=26257
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: on-failure
    networks:
      - backend_network

  bot:
    build: ./bot
    container_name: bot
    depends_on:
      api:
        condition: service_healthy
    environment:
      - API_HOST=api
      - API_PORT=8090
    restart: on-failure
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  roach1:
  roach2: